# -*- mode: python ; coding: utf-8 -*-

import os
import sys
from pathlib import Path

_PROJECT_ROOT = Path.cwd()
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

datas = []

templates_src = _PROJECT_ROOT / "privacybox" / "templates" / "builtins"
if templates_src.is_dir():
    for f in templates_src.glob("*.yaml"):
        datas.append((str(f), "privacybox/templates/builtins"))

a = Analysis(
    ["privacybox/__main__.py"],
    pathex=[str(_PROJECT_ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=[
        "privacybox",
        "privacybox.cli",
        "privacybox.cli.commands",
        "privacybox.cli.commands.deploy",
        "privacybox.cli.commands.manage",
        "privacybox.cli.commands.config_cmd",
        "privacybox.cli.commands.template_cmd",
        "privacybox.cli.commands.credential_cmd",
        "privacybox.cli.commands.doctor_cmd",
        "privacybox.config",
        "privacybox.config.loader",
        "privacybox.config.schema",
        "privacybox.config.wizard",
        "privacybox.engine",
        "privacybox.llm",
        "privacybox.llm.ollama_provider",
        "privacybox.llm.openai_provider",
        "privacybox.llm.claude_provider",
        "privacybox.llm.base",
        "privacybox.runtime",
        "privacybox.runtime.docker_backend",
        "privacybox.runtime.base",
        "privacybox.templates",
        "privacybox.templates.renderer",
        "privacybox.templates.registry",
        "privacybox.templates.builtins",
        "privacybox.templates.params",
        "privacybox.state",
        "privacybox.state.database",
        "privacybox.state.migrations",
        "privacybox.credentials",
        "privacybox.credentials.store",
        "privacybox.credentials.backends",
        "privacybox.credentials.backends.base",
        "privacybox.credentials.backends.keychain_backend",
        "privacybox.privacy",
        "privacybox.privacy.proxy",
        "privacybox.plugins",
        "privacybox.plugins.interfaces",
        "privacybox.remote",
        "privacybox.cicd",
        "privacybox.cicd.actions",
        "privacybox.doctor",
        "privacybox.install_config",
        "privacybox.utils",
        "questionary",
        "yaml",
        "rich",
        "typer",
        "jinja2",
        "pydantic",
        "cryptography",
        "docker",
        "httpx",
        "platformdirs",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "unittest",
        "http.server",
        "pydoc",
        "test",
        "distutils",
        "setuptools",
        "pip",
        "numpy",
        "matplotlib",
        "scipy",
        "pandas",
        "PIL",
        "cv2",
        "tensorflow",
        "torch",
        "IPython",
        "jupyter",
        "notebook",
        "bottle",
        "flask",
        "django",
        "sphinx",
        "pytest",
        "nose",
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="PrivacyBox",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version=None,
)
